version: '3.4'

services:
  bugreporter.frontend:
    image: ${DOCKER_REGISTRY-}bugreporterfrontend
    build:
      context: ./BugReporter.FrontEnd
      dockerfile: Dockerfile
    ports:
    - "1234:80" 
    networks:
        - my-network
    depends_on:
        - "bugreporter.bugapi"

  bugreporter.database:
    image: ${DOCKER_REGISTRY-}bugreporterdatabase
    build:
      context: ./BugReporter.Database
      dockerfile: Dockerfile
    ports:
        - "1337:80"
    networks:
        - my-network

  bugreporter.bugapi:
    image: ${DOCKER_REGISTRY-}bugreporterbugapi
    build:
      context: ./BugReporter.BugApi
      dockerfile: Dockerfile
    ports:
        - "1336:80" 
    networks:
        - my-network

networks:
  my-network:
    external: false