version: '3.4'

services:
  bugreporter.bugapi:
    image: ${DOCKER_REGISTRY-}bugreporterbugapi
    build:
      context: .
      dockerfile: BugReporter.BugApi/Dockerfile

  bugreporter.database:
    image: ${DOCKER_REGISTRY-}bugreporterdatabase
    build:
      context: .
      dockerfile: BugReporter.Database/Dockerfile


  bugreporter.frontend:
    image: ${DOCKER_REGISTRY-}bugreporterfrontend
    build:
      context: .
      dockerfile: BugReporter.FrontEnd/Dockerfile

