version: '3.4'

services:
  bugreporter.database:
    image: ${DOCKER_REGISTRY-}bugreporterdatabase
    build:
      context: .
      dockerfile: BugReporter.Database/Dockerfile

  bugreporter.bugapi:
    image: ${DOCKER_REGISTRY-}bugreporterbugapi
    build:
      context: .
      dockerfile: BugReporter.BugApi/Dockerfile


  bugreport.frontend:
    image: ${DOCKER_REGISTRY-}bugreportfrontend
    build:
      context: .
      dockerfile: BugReport.Frontend/Dockerfile

